config/routes.rb
Rails.application.routes.draw do
  root :to => 'users#index'
  resources :users do
    resources :prints, only: [:new, :create]
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/print.rb
class Print < ActiveRecord::Base
  belongs_to :user
  
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :prints
  attr_accessor :password

  validates_confirmation_of :password
  before_save :encrypt_password

  validates :name, :presence => true
  validates :email, :presence => true
  validates :password, :presence => true
  validates :password_confirmation, :presence => true
  validates_uniqueness_of :email

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    if @user != current_user
      flash[:notice] = "Not your page, buster!"
      redirect_to users_path
    end
    @print = Print.new
  end

  def create
    @user = User.find(params[:user_id])
    @print = @user.prints.new(print_params)
    if @print.save
      flash[:notice] = "Print added!"
      redirect_to user_path(@user)
    else
      flash[:alert] = "Your print slipped through our paws... Please try again."
      render :new
    end
  end

private
  def print_params
    params.require(:print).permit(:image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem logging you in."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now logged out."
    redirect_to users_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the site!"
      redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      flash[:notice] = "Not your page, buster!"
      redirect_to users_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = @user.name + "'s details edited!"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    session[:user_id] = nil
    @user.destroy
    flash[:notice] = "Record destroyed!"
    redirect_to users_path
  end

private
  def user_params
    params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix the following errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paw Prints</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <!-- <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet"> -->
</head>
<body>

 <div class="container">
    <div class="row">
      <div class="col-md-12 center">
        <h1><%= link_to "Paw Prints", users_path %></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 center">
        <p>
          <i class="fa fa-connectdevelop"></i>
          <%= link_to new_user_path do %>Register<% end %>
          <i class="fa fa-connectdevelop"></i>
          <% if current_user %>
            <%= link_to session_path(current_user), :data => { :method => :delete } do %>Logout<% end %>
          <% else %>
            <%= link_to new_session_path do %>Login<% end %>
          <% end %>
        <i class="fa fa-connectdevelop"></i></p>
        <hr>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 center">
        <%= flash[:alert] %>
        <%= flash[:notice] %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/prints/new.html.erb
<h4>Prints</h4>
<%= form_for [@user, @print], :html => { :multipart => true} do |f| %>
  <ul class="formList list-unstyled well">
    <li>
      <%= f.label :image %>
      <%= f.file_field :image %>
    </li>

    <li class="submit">
      <%= f.submit "Print", :class => "btn btn-primary" %>
    </li>
  </ul>
<% end %>

app/views/users/_form.html.erb
<%= render "layouts/errors", :object => @user %>

<%= form_for @user, :html => { :mulitpart => true} do |f| %>
  <ul class="formList list-unstyled">
    <li>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </li>

    <li>
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </li>

    <li>
      <%= f.label :password %><br>
      <%= f.password_field :password %>
    </li>

    <li>
      <%= f.label :password_confirmation %><br>
      <%= f.password_field :password_confirmation %>
    </li>

    <li>
      <%= f.label :avatar %>
      <%= f.file_field :avatar, :class => "well" %>
    </li>

    <li class="submit">
      <%= f.submit "Submit", :class => "btn btn-primary" %>
    </li>
  </ul>
<% end %>

app/views/users/edit.html.erb
<h2>Edit User Info</h2>


<%= render "form" %>

app/views/users/index.html.erb
<h2>Welcome to Paw Prints!</h2>
<h3>The site for pets to get frisky and start snapping cute pix.</h3>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>New User</h2>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= render "form" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
    <%= image_tag @user.avatar.url(:medium) %>
    <h3><%= @user.name %></h3>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <%= link_to "Add a new Print", new_user_print_path(current_user) %>
    <% if @user.prints.any? %>
      <hr>
      <div class="row">
        <% @user.prints.each do |image| %>
          <div class="col-md-2 inline">
            <%= link_to (image_tag image.image.url(:thumb)), image.image.url %>
          </div>
        <% end %>
      </div>
      <hr>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12 center">
    <p>
      <%= link_to "Return Home", users_path %> |
      <%= link_to edit_user_path(@user) do %><i id="edit" class="fa fa-cog"></i> Edit<% end %> |
      <%= link_to user_path(@user), :data => {:confirm => "You sure you want to delete this?", :method => "delete"} do %><i class="fa fa-trash-o"></i> Delete<% end %>
    </p>
  </div>
</div>